list: $/liip/events/models/event/columns.yaml
modelClass: Liip\Events\Models\Event
title: Events
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'liip/events/events/update/:id'
